apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bid-service-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /bids.v1.
        pathType: Prefix
        backend:
          service:
            name: bid-service
            port:
              number: 80
