global:
  postgresql:
    auth:
      postgresPassword: password
      username: user
      password: password
      database: bid_db

primary:
  persistence:
    enabled: false # Ephemeral for local dev

